---
layout: cv
title: Packer Wittwer's CV
---
# Packer Wittwer
Craftsman, nerd, musician, student.

<div id="webaddress">
<a href="https://musical-dollop-woqq181.pages.github.io/">Packer Wittwer DS 250 Portfolio</a>
</div>


## Currently

Swimming on a sea of learning :\)

### Specializing in

All things computer related! I haven't decided on a niche yet, so persuade me to join yours.


### Research interests

Computing, data, programming and development, networks, cybersecurity.


## Education

`2012-2016`
__Shelley High School - Shelley, Idaho__

`August 2019 - Current`
__Brigham Young University - Idaho__

- Computer Science

## Awards

`2016`
Eagle Scout, *Boy Scouts of America*


## Occupation

`2018 - Current`
__Disability Aid__, - Consumer Direct Care

- Assisted with activities of daily living 
- Emotional and social support
- Communication 
- Documentation and record keeping 

## Skills
- Chinese (Mandarin), moderate fluency
- Communication
- Tenacity
- Integrity
- Love of learning
- Willing to work hard

<!-- ### Footer

Last updated: May 2013 -->